# Generated by Django 3.0.7 on 2020-09-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='images/posters/movie_camera.png', upload_to='images/posters/'),
        ),
    ]
